definitions:
  handler.Response:
    properties:
      data: {}
      description:
        type: string
      status:
        type: integer
    type: object
  models.Account:
    properties:
      balance:
        type: number
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
      phone:
        type: string
      updated_at:
        type: string
    type: object
  models.CreateAccount:
    properties:
      balance:
        type: number
      name:
        type: string
      phone:
        type: string
    type: object
  models.Deposit:
    properties:
      amount:
        type: number
      id:
        type: string
    type: object
  models.Withdraw:
    properties:
      amount:
        type: number
      id:
        type: string
    type: object
info:
  contact: {}
paths:
  /accounts:
    post:
      consumes:
      - application/json
      description: Create Account
      operationId: create_account
      parameters:
      - description: CreateAccountRequestBody
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/models.CreateAccount'
      produces:
      - application/json
      responses:
        "200":
          description: AccountBody
          schema:
            allOf:
            - $ref: '#/definitions/handler.Response'
            - properties:
                data:
                  $ref: '#/definitions/models.Account'
              type: object
        "400":
          description: Invalid Argument
          schema:
            allOf:
            - $ref: '#/definitions/handler.Response'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Server Error
          schema:
            allOf:
            - $ref: '#/definitions/handler.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: Create Account
      tags:
      - Account
  /accounts/{id}/balance:
    get:
      consumes:
      - application/json
      description: Get Balance
      operationId: get_balance
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: GetListBranchResponseBody
          schema:
            allOf:
            - $ref: '#/definitions/handler.Response'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: Invalid Argument
          schema:
            allOf:
            - $ref: '#/definitions/handler.Response'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Server Error
          schema:
            allOf:
            - $ref: '#/definitions/handler.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: Get Balance
      tags:
      - Balance
  /accounts/{id}/deposit:
    post:
      consumes:
      - application/json
      description: Deposit Account
      operationId: deposit
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      - description: DepositRequestBody
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/models.Deposit'
      produces:
      - application/json
      responses:
        "200":
          description: Account
          schema:
            allOf:
            - $ref: '#/definitions/handler.Response'
            - properties:
                data:
                  $ref: '#/definitions/models.Deposit'
              type: object
        "400":
          description: Invalid Argument
          schema:
            allOf:
            - $ref: '#/definitions/handler.Response'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Server Error
          schema:
            allOf:
            - $ref: '#/definitions/handler.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: Deposit Account
      tags:
      - Deposit
  /accounts/{id}/withdraw:
    post:
      consumes:
      - application/json
      description: Withdraw Account
      operationId: withdraw
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      - description: WithdrawRequestBody
        in: body
        name: object
        required: true
        schema:
          $ref: '#/definitions/models.Withdraw'
      produces:
      - application/json
      responses:
        "200":
          description: Account
          schema:
            allOf:
            - $ref: '#/definitions/handler.Response'
            - properties:
                data:
                  $ref: '#/definitions/models.Withdraw'
              type: object
        "400":
          description: Invalid Argument
          schema:
            allOf:
            - $ref: '#/definitions/handler.Response'
            - properties:
                data:
                  type: string
              type: object
        "500":
          description: Server Error
          schema:
            allOf:
            - $ref: '#/definitions/handler.Response'
            - properties:
                data:
                  type: string
              type: object
      summary: Withdraw Account
      tags:
      - Withdraw
swagger: "2.0"
